# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  profile = "anton"

  assume_role {
    session_name = "lesson-160"
    role_arn = "arn:aws:iam::626562454521:role/terraform" 
  }
}
