# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-tutorial-backend-tf-state"
    dynamodb_table = "terragrunt-tutorial-tf-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "anton"
    region         = "us-east-1"
    role_arn       = "arn:aws:iam::626562454521:role/terraform"
  }
}
